import type { GrowthReportContent } from "./schema";

export const placeholderReport: GrowthReportContent = {
  companyName: "Acme Wellness",
  websiteUrl: "acmewellness.com",
  preparedDate: "9 March 2026",
  preparedFor: "Acme Wellness",
  dataSources: [
    "SimilarWeb",
    "SE Ranking/Ahrefs",
    "Automated SEO crawler (15 pages)",
    "TikTok",
    "Instagram",
    "LinkedIn",
    "Reddit",
    "Trustpilot",
    "Tracxn",
    "Crunchbase",
  ],
  keyMetrics: {
    monthlyVisits: { value: "1.2M", status: "good" },
    countryRank: { value: "#1,450", status: "warning" },
    domainRating: { value: "58", status: "warning" },
    onSiteScore: { value: "72/100", status: "warning" },
    searchTraffic: { value: "44.2%", status: "warning" },
    backlinks: { value: "12,400", status: "info" },
    igFollowers: { value: "180K", status: "good" },
    tiktokFollowers: { value: "15.3K", status: "warning" },
    linkedinFollowers: { value: "8,200", status: "info" },
  },
  executiveSummary: {
    overview:
      "This report is the complete output of a full SEO and growth audit of acmewellness.com. It covers 15 pages of on-site technical audit, traffic and domain authority analysis, competitive benchmarking against 5 competitors, LinkedIn post analysis, social media presence, AI engine visibility, and a full channel distribution strategy. All findings are data-backed from live scrapes.",
    keyConclusion:
      "Acme Wellness has strong brand recognition and growing traffic, but is leaving significant organic growth on the table through fixable technical gaps, underused social audiences, and zero AI engine visibility. This report identifies 20 specific initiatives, stack-ranked by impact-to-effort ratio.",
  },
  trafficAnalysis: {
    dataSource: "SimilarWeb (February 2026 snapshot)",
    metrics: [
      { metric: "Global Rank", value: "#35,400" },
      { metric: "UK Rank", value: "#1,450" },
      { metric: "Health Category Rank", value: "#42" },
      { metric: "Monthly Visits (Feb 2026)", value: "1,200,000" },
      { metric: "Bounce Rate", value: "46.2%" },
      { metric: "Pages per Visit", value: "3.2" },
      { metric: "Avg Visit Duration", value: "2m 05s" },
      { metric: "Primary Market", value: "UK (72% of traffic)" },
    ],
    trafficSources: { search: "44.2%", direct: "38.5%", referral: "6.1%", social: "3.8%" },
    findings: [
      "Bounce rate of 46.2%: Slightly above e-commerce avg (45%). Room for landing page optimisation.",
      "Search at 44.2%: Below target of 55%+. Opportunity to grow organic share.",
      "Social at 3.8%: 180K IG followers driving minimal site traffic. Conversion rate ~0.02%.",
      "Geographic: 72% UK. Opportunity for US/EU expansion with hreflang tags.",
    ],
  },
  domainAuthority: {
    dataSource: "SE Ranking / Ahrefs metrics",
    metrics: [
      { metric: "Domain Rating (DR)", value: "58 / 100" },
      { metric: "Total Backlinks", value: "12,400" },
      { metric: "Referring Domains", value: "890" },
      { metric: "Dofollow Backlinks", value: "210" },
      { metric: "Dofollow Referring Domains", value: "145" },
    ],
    findings: [
      "DR 58 is solid but below top competitors (DR 65-76): Link building is the primary lever.",
      "Dofollow ratio is low: Only 210 dofollow backlinks. Most links are nofollow from press/social.",
      "890 referring domains: Reasonable diversity. Target: 1,500+ domains within 12 months.",
    ],
    linkOpportunities: [
      "Brand stockist pages: Major brands stocked should link to retailer pages.",
      "PR/investment coverage: Target dofollow placements in press coverage.",
      "Expert advisor content: Leverage advisory board for expert roundups and contributed articles.",
      "Blog outreach: Use existing content as citation sources for health journalists/bloggers.",
    ],
  },
  siteAudit: {
    dataSource: "Automated SEO crawler (homepage + 4 collections + 5 PDPs + 3 blog posts + About Us)",
    summaryStats: { pagesAudited: 15, avgScore: 72, errors404: 1 },
    categoryScores: { "Meta Tags": 78, Headings: 55, Content: 60, Technical: 90, Schema: 45, Performance: 95 },
    pageBreakdown: [
      {
        page: "Top Blog Post",
        score: 90,
        meta: 95,
        headings: 100,
        content: 70,
        technical: 100,
        schema: 70,
        words: "2,800",
        type: "Blog",
      },
      {
        page: "Blog Post #2",
        score: 85,
        meta: 75,
        headings: 100,
        content: 70,
        technical: 100,
        schema: 70,
        words: "1,500",
        type: "Blog",
      },
      {
        page: "Product A",
        score: 76,
        meta: 90,
        headings: 20,
        content: 65,
        technical: 100,
        schema: 70,
        words: "1,100",
        type: "Product",
      },
      {
        page: "Product B",
        score: 74,
        meta: 85,
        headings: 20,
        content: 65,
        technical: 100,
        schema: 70,
        words: "980",
        type: "Product",
      },
      {
        page: "Homepage",
        score: 73,
        meta: 80,
        headings: 20,
        content: 65,
        technical: 100,
        schema: 65,
        words: "850",
        type: "Home",
      },
      {
        page: "About Us",
        score: 70,
        meta: 60,
        headings: 90,
        content: 60,
        technical: 80,
        schema: 20,
        words: "400",
        type: "Info",
      },
      {
        page: "/collections/main",
        score: 66,
        meta: 85,
        headings: 20,
        content: 60,
        technical: 80,
        schema: 20,
        words: "500",
        type: "Collection",
      },
      {
        page: "/collections/new",
        score: 64,
        meta: 80,
        headings: 20,
        content: 55,
        technical: 80,
        schema: 20,
        words: "450",
        type: "Collection",
      },
    ],
    criticalIssues: [
      "H1 structure broken on 8+ pages: Third-party widget injects rogue H1 tags on collection and product pages.",
      "Collection pages have no structured data: Score 20/100 on schema. Missing CollectionPage + ItemList markup.",
      "1 broken URL (404): Confirmed via automated crawl. Losing link equity.",
      "Image alt text gaps: Template-level images missing alt text on every page.",
      "Meta description inconsistencies: Some product pages exceed 160 chars, some blog posts missing entirely.",
    ],
  },
  competitiveBenchmarking: {
    dataSources: "SimilarWeb (Feb 2026), Ahrefs DR",
    competitors: [
      {
        site: "Competitor A",
        visits: "5.2M",
        countryRank: "#320",
        dr: "72",
        backlinks: "850K",
        refDomains: "8,200",
        search: "60.1%",
        bounce: "48.5%",
        pagesPerVisit: "3.8",
      },
      {
        site: "Competitor B",
        visits: "3.1M",
        countryRank: "#650",
        dr: "65",
        backlinks: "95K",
        refDomains: "3,100",
        search: "55.4%",
        bounce: "43.2%",
        pagesPerVisit: "4.9",
      },
      {
        site: "Acme Wellness",
        visits: "1.2M",
        countryRank: "#1,450",
        dr: "58",
        backlinks: "12.4K",
        refDomains: "890",
        search: "44.2%",
        bounce: "46.2%",
        pagesPerVisit: "3.2",
      },
      {
        site: "Competitor C",
        visits: "800K",
        countryRank: "#2,100",
        dr: "52",
        backlinks: "5.8K",
        refDomains: "620",
        search: "42.8%",
        bounce: "49.1%",
        pagesPerVisit: "2.8",
      },
    ],
    findings: [
      "Acme has the 3rd best bounce rate in the set (46.2%): Outperforms Competitor C (49.1%).",
      "DR 58 beats Competitor C (52) but trails Competitor A (72) significantly: Primary authority gap.",
      "Search share gap vs Competitor A: 44.2% vs 60.1%. Matching their share = +190K monthly visits from search.",
      "Referring domain gap: 890 vs Competitor A 8,200. Primary authority gap to close.",
    ],
  },
  contentAudit: {
    dataSource: "Automated SEO crawler (3 blog posts crawled)",
    articles: [
      {
        article: "Top Performing Article",
        score: "90",
        metaDesc: "\u2713",
        h1: "\u2713",
        schema: "Article",
        words: "2,800",
        status: "Exemplary",
      },
      {
        article: "Article #2",
        score: "85",
        metaDesc: "\u2717",
        h1: "\u2713",
        schema: "Article",
        words: "1,500",
        status: "Missing meta desc",
      },
      {
        article: "Article #3 (broken)",
        score: "-",
        metaDesc: "-",
        h1: "-",
        schema: "-",
        words: "-",
        status: "404 - URL broken",
      },
    ],
    findings: [
      "Blog content is the strongest SEO asset on the site: Blog posts score 85-90/100 vs 64-76 for other page types.",
      "Top article is the template: 2,800 words, proper H1, Article schema, 90/100. Blueprint for all future content.",
      "Broken URL detected: One blog post returns 404. Existing backlinks and rankings being lost.",
      "Blog-to-product internal linking needs strengthening: Deep-link to specific PDPs, not just collection pages.",
    ],
  },
  linkedinAudit: {
    dataSources: "LinkedIn company page scraper, profile scraper, post scraper",
    profiles: [
      { label: "COMPANY FOLLOWERS", name: "Company", followers: "8,200" },
      { label: "CEO", name: "Jane Smith", followers: "2,400" },
      { label: "CO-FOUNDER", name: "John Doe", followers: "1,800" },
    ],
    engagementStats: [
      { label: "CO. ENG RATE", value: "0.35%" },
      { label: "CEO ENG RATE", value: "3.2%" },
      { label: "CO-FOUNDER POSTS", value: "0" },
    ],
    companyThemes: [
      {
        theme: "Milestone",
        count: 5,
        avgLikes: "120",
        avgComments: "10",
        avgReposts: "8",
        assessment: "Top performer. Award wins and growth metrics drive highest engagement.",
      },
      {
        theme: "Product",
        count: 4,
        avgLikes: "85",
        avgComments: "5",
        avgReposts: "3",
        assessment: "Solid. Product launches get consistent engagement.",
      },
      {
        theme: "Event",
        count: 8,
        avgLikes: "60",
        avgComments: "4",
        avgReposts: "5",
        assessment: "Over-indexed at 35%. Diminishing returns after repeat posts.",
      },
      {
        theme: "Hiring",
        count: 5,
        avgLikes: "40",
        avgComments: "3",
        avgReposts: "2",
        assessment: "Lowest engagement. Consider reducing volume.",
      },
    ],
    founderPosts: [
      {
        post: "Vision/philosophy post",
        likes: 180,
        comments: 15,
        engRate: "5.2%",
        hook: "9/10",
        cta: "6/10",
        story: "8/10",
        score: 82,
      },
      {
        post: "Growth milestone",
        likes: 140,
        comments: 20,
        engRate: "4.0%",
        hook: "8/10",
        cta: "5/10",
        story: "7/10",
        score: 72,
      },
      {
        post: "Industry insight",
        likes: 95,
        comments: 8,
        engRate: "2.8%",
        hook: "7/10",
        cta: "7/10",
        story: "6/10",
        score: 65,
      },
    ],
    findings: [
      "CEO engagement rate of 3.2% is strong (2-4x benchmark): Volume is the bottleneck — only ~5 visible posts.",
      "Co-founder is completely untapped: 1,800 followers, zero posts. Immediate activation opportunity.",
      "Company page over-indexes on events (35%) and hiring (22%): Shift to milestones and product content.",
    ],
  },
  socialSeo: {
    dataSources: "TikTok Profile Scraper, Instagram search index, SimilarWeb",
    coreProblem:
      "The core problem: 180K Instagram followers generating only 3.8% of site traffic. That's a ~0.02% conversion rate. If Acme converted 3% of IG followers monthly, that's +5,400 visits/month from Instagram alone.",
    platforms: [
      { platform: "Instagram", followers: "180,000", content: "620 posts", trafficImpact: "~1.5% of 3.8% social" },
      { platform: "TikTok", followers: "15,300", content: "400 videos", trafficImpact: "Minimal" },
      { platform: "LinkedIn", followers: "8,200 (co)", content: "22 company posts", trafficImpact: "Referral only" },
    ],
    findings: [
      "TikTok keyword strategy: 400 videos but only 15.3K followers = low discoverability. Script around search keywords.",
      "Pinterest opportunity: High-intent wellness audience. Blog content is highly pinnable. Currently unmeasured.",
      "Cross-channel content flooding: Deploy same keyword themes across blog + TikTok + IG + LinkedIn + Reddit.",
    ],
  },
  aiVisibility: {
    dataSources: "Direct URL analysis (robots.txt, llms.txt), Google SERP",
    botStatus: [
      {
        bot: "OAI-SearchBot",
        status: "\u2717 Not mentioned",
        impact: "ChatGPT real-time search",
        action: "Add Allow directive",
      },
      { bot: "GPTBot", status: "\u2717 Not mentioned", impact: "ChatGPT training", action: "Block (protect content)" },
      {
        bot: "PerplexityBot",
        status: "\u2717 Not mentioned",
        impact: "Perplexity search",
        action: "Add Allow directive",
      },
      { bot: "llms.txt", status: "\u2717 404 Not Found", impact: "LLM comprehension", action: "Create file" },
      {
        bot: "robots.txt AI policy",
        status: "\u2717 Standard only",
        impact: "All AI engines",
        action: "Add AI directives",
      },
    ],
    shareOfModel: [
      { query: '"Best [category] UK"', result: "\u2717 Absent", whoRanks: "Amazon, Competitor A, Boots" },
      { query: '"Best [product type] UK buy"', result: "\u2717 Absent", whoRanks: "Competitor B, Amazon, H&B" },
    ],
    findings: [
      "Company is completely absent from Google for category-level queries: Traffic is almost entirely branded search + direct.",
      "No AI comprehension file exists: Zero AI engine visibility.",
      "Cracking category organic discovery: The single biggest growth opportunity.",
    ],
  },
  entitySeo: {
    dataSources: "Trustpilot, Tracxn, Crunchbase, Google search",
    platforms: [
      { platform: "Google Brand Profile", status: "\u2717 Not found", data: "N/A", action: "Claim immediately" },
      { platform: "Trustpilot", status: "\u2713 Active", data: "2,500 reviews, 4.8 stars", action: "Maintain" },
      { platform: "Tracxn", status: "\u2713 Listed", data: "Founded 2020, $1.2M raised", action: "Verify accuracy" },
      { platform: "Crunchbase", status: "\u2713 Listed", data: "$1.8M, 25 employees", action: "Conflicts with Tracxn" },
    ],
    findings: [
      "Entity data inconsistencies: Founding year varies, employee count differs across platforms.",
      "No Google Business Profile: Should be claimed immediately for Knowledge Graph presence.",
      "Trustpilot is the strongest signal: 2,500 reviews at 4.8 stars. Ensure widget visible on homepage.",
    ],
  },
  linkedinStrategy: {
    people: [
      {
        name: "Jane Smith (CEO)",
        role: "CEO",
        frequency: "3-4 posts/week",
        themes: [
          {
            theme: "Founder Philosophy",
            pct: "40%",
            description: "Hard truths of building a wellness company. Vision and conviction posts.",
          },
          {
            theme: "Behind the Build",
            pct: "25%",
            description: "Revenue milestones, team wins, investor conversations. Be specific with numbers.",
          },
          {
            theme: "Industry Conviction",
            pct: "20%",
            description: "Personal expertise, product opinions. Background gives credibility.",
          },
          { theme: "Talent & Culture", pct: "15%", description: "Aspirational hiring posts with clear asks." },
        ],
      },
      {
        name: "John Doe (Co-founder)",
        role: "Co-founder",
        frequency: "2 posts/week to start",
        themes: [
          {
            theme: "Origin Story",
            pct: "30%",
            description: "The career pivot story. Lessons, mistakes, why they co-founded.",
          },
          {
            theme: "Product & Curation",
            pct: "30%",
            description: "Deep-dives into product decisions. Own the 'product brain' positioning.",
          },
          {
            theme: "Operations",
            pct: "25%",
            description: "E-commerce metrics, tech decisions, logistics. Attracts B2B attention.",
          },
          {
            theme: "Co-Founder Dynamic",
            pct: "15%",
            description: "Working together, division of responsibilities. Naturally compelling.",
          },
        ],
      },
    ],
    companyRebalance: [
      { theme: "Milestone", current: "15%", target: "25%", change: "\u2191 +10%" },
      { theme: "Product/Brand", current: "12%", target: "25%", change: "\u2191 +13%" },
      { theme: "Philosophy", current: "10%", target: "20%", change: "\u2191 +10%" },
      { theme: "Event", current: "35%", target: "15%", change: "\u2193 -20%" },
      { theme: "Hiring", current: "22%", target: "10%", change: "\u2193 -12%" },
    ],
  },
  masterStrategy: {
    initiatives: [
      {
        num: 1,
        initiative: "Fix H1/heading structure",
        impact: "Critical",
        effort: "Low",
        timeline: "Week 1",
        owner: "Eng",
        category: "Tech",
        metric: "Score +12pts",
        note: "Every page affected",
      },
      {
        num: 2,
        initiative: "Redirect broken 404 URLs",
        impact: "Critical",
        effort: "Low",
        timeline: "Week 1",
        owner: "Eng",
        category: "Tech",
        metric: "Link equity",
        note: "1 confirmed broken URL",
      },
      {
        num: 3,
        initiative: "llms.txt + AI bot robots.txt",
        impact: "High",
        effort: "Low",
        timeline: "Week 1",
        owner: "Eng",
        category: "AI",
        metric: "AI eligibility",
        note: "Zero cost, high upside",
      },
      {
        num: 4,
        initiative: "Fix template alt tags",
        impact: "High",
        effort: "Low",
        timeline: "Week 1",
        owner: "Eng",
        category: "Tech",
        metric: "Image score +5",
        note: "5-minute fix",
      },
      {
        num: 5,
        initiative: "Collection page schema",
        impact: "Critical",
        effort: "Med",
        timeline: "Sprint 1",
        owner: "Eng",
        category: "Tech",
        metric: "Schema 20\u219270",
        note: "Enables rich snippets",
      },
      {
        num: 6,
        initiative: "Blog meta descriptions",
        impact: "High",
        effort: "Low",
        timeline: "Sprint 1",
        owner: "Content",
        category: "Tech",
        metric: "CTR +10-20%",
        note: "Some missing",
      },
      {
        num: 7,
        initiative: "Brand stockist links",
        impact: "High",
        effort: "Med",
        timeline: "Sprint 1",
        owner: "Growth",
        category: "Auth",
        metric: "+15-20 links",
        note: "Retailer pages",
      },
      {
        num: 8,
        initiative: "Claim Google Brand Profile",
        impact: "High",
        effort: "Low",
        timeline: "Sprint 1",
        owner: "Mktg",
        category: "Entity",
        metric: "Knowledge Graph",
        note: "E-commerce eligible",
      },
      {
        num: 9,
        initiative: "CEO LinkedIn strategy",
        impact: "High",
        effort: "Med",
        timeline: "Sprint 1",
        owner: "Content",
        category: "LI",
        metric: "Eng 3%\u21925%+",
        note: "Scale to 12+ posts/mo",
      },
      {
        num: 10,
        initiative: "Co-founder activation",
        impact: "Medium",
        effort: "Med",
        timeline: "Sprint 1",
        owner: "Content",
        category: "LI",
        metric: "0\u21924+ posts/mo",
        note: "Untapped asset",
      },
    ],
  },
  measurementFramework: {
    targets: [
      { label: "TRAFFIC", value: "1.2M\u21921.8M", status: "info" },
      { label: "SEARCH SHARE", value: "44%\u219255%", status: "warning" },
      { label: "DR", value: "58\u219265+", status: "warning" },
      { label: "REF DOMAINS", value: "890\u21921.5K+", status: "info" },
      { label: "COUNTRY RANK", value: "#1,450\u2192#1,000", status: "info" },
      { label: "AI CITATIONS", value: "Top 5", status: "bad" },
    ],
    cadence: [
      "Weekly: Automated site crawl (50 pages), broken link check, index coverage monitor.",
      "Monthly: SimilarWeb traffic pull, DR/backlink check, SoM prompt testing, LinkedIn analytics review.",
      "Quarterly: Full competitor benchmark refresh, strategy review, KPI assessment.",
      "Ongoing: GSC monitoring (once granted), social search tracking, Reddit presence.",
    ],
  },
  redditAudit: {
    dataSource: "Reddit search scraper (50 results, all time)",
    overview:
      "We scraped Reddit for all mentions of the brand. Out of 50 results returned, 6 were genuine brand mentions, 3 were referral/discount spam, and the rest were unrelated.",
    summaryStats: { brandMentions: "6", sentiment: "Mixed", topSubreddits: "3" },
    mentions: [
      {
        post: "Negative UX complaint",
        subreddit: "r/assholedesign",
        score: "150",
        comments: "8",
        type: "Negative",
        detail: "Complaint about confusing checkout. High visibility.",
      },
      {
        post: "Is this site legit?",
        subreddit: "r/Supplements",
        score: "8",
        comments: "12",
        type: "Trust query",
        detail: "User asking about legitimacy. Mixed responses.",
      },
      {
        post: "Good experience review",
        subreddit: "r/wellness",
        score: "5",
        comments: "3",
        type: "Positive",
        detail: "Genuine positive review from customer.",
      },
    ],
    findings: [
      "Brand awareness exists on Reddit but trust lags behind: Multiple 'is it legit?' queries.",
      "One negative UX complaint has highest visibility: Should be addressed.",
      "No official brand presence on Reddit: Zero value-first content posted.",
    ],
    recommendations: [
      "Build authority in relevant subreddits: Genuine, value-first content approach.",
      "Address trust questions proactively: Transparency about processes and sourcing.",
      "Fix any UX issues highlighted in negative posts: Checkout flow is the main complaint.",
    ],
  },
  caseStudies: [
    {
      title: "ElevenLabs: #1 for Core AI Voice Keywords",
      subtitle:
        "ElevenLabs is the world's leading AI voice platform. MVRX Labs was engaged to drive organic search growth.",
      details: [
        { label: "Client", value: "ElevenLabs (Series B, $1B+ valuation)" },
        { label: "Objective", value: "Rank #1 for 'text to speech', 'voice cloning', 'AI voice generator'" },
        { label: "Process", value: "Built and shipped best-in-class, SEO-optimised site and landing pages." },
        { label: "Impact", value: "100x SEO traffic growth. 20% of total traffic from non-branded organic." },
      ],
    },
    {
      title: "Recraft: Page 1 for AI Image Generation Keywords",
      subtitle: "Recraft is an AI design platform. MVRX Labs was engaged to build organic search visibility.",
      details: [
        { label: "Client", value: "Recraft (AI image generation platform)" },
        {
          label: "Objective",
          value: "Page 1 for 'AI icon generator', 'AI wallpaper generator' and long-tail keywords",
        },
        {
          label: "Process",
          value: "Best-in-class SEO foundations. Programmatically generated targeted use-case pages.",
        },
        { label: "Impact", value: "10x non-branded organic traffic. 15% of total traffic from organic search." },
      ],
    },
  ],
  statementOfWork: {
    scopeDescription: "MVRX Labs will provide end-to-end SEO and growth execution across three workstreams:",
    workstreams: [
      "Technical SEO and Site Optimisation: Heading fixes, schema, broken URLs, meta descriptions, alt text, AI bot policy, product page standardisation.",
      "Content and Channel Strategy: LinkedIn ghostwriting for founders, SEO blog content, social SEO activation, Reddit community building.",
      "Authority and Visibility: Dofollow link building, Google Brand Profile, entity data cleanup, Share of Model tracking, competitive benchmarking.",
    ],
    deliverables: [
      { deliverable: "Technical SEO roadmap", frequency: "One-off (Week 1-2)", format: "Doc with ticket specs" },
      { deliverable: "Schema markup templates", frequency: "One-off (Sprint 1)", format: "Code files" },
      { deliverable: "llms.txt + robots.txt", frequency: "One-off (Week 1)", format: "Plain text files" },
      { deliverable: "LinkedIn content (CEO)", frequency: "3-4 posts/week", format: "Drafts for review" },
      { deliverable: "LinkedIn content (Co-founder)", frequency: "2 posts/week", format: "Drafts for review" },
      { deliverable: "SEO blog articles", frequency: "2-4 per month", format: "3,000+ word articles" },
      { deliverable: "Link building outreach", frequency: "Ongoing", format: "25+ new domains/quarter" },
      { deliverable: "Monthly performance report", frequency: "Monthly", format: "Traffic, DR, rankings" },
    ],
    timeline: [
      {
        phase: "Phase 1: Foundation",
        timing: "Weeks 1-2",
        milestones: "Quick wins deployed. llms.txt live. Broken URLs redirected. LinkedIn started.",
      },
      {
        phase: "Phase 2: Infrastructure",
        timing: "Weeks 3-6",
        milestones: "Schema live. Stockist outreach started. First blog articles published.",
      },
      {
        phase: "Phase 3: Scale",
        timing: "Weeks 7-12",
        milestones: "Full LinkedIn cadence. 6-8 blog articles. 25+ new referring domains.",
      },
      {
        phase: "Phase 4: Optimise",
        timing: "Months 4-6",
        milestones: "Product page standardisation at scale. SoM tracking. Social activation.",
      },
    ],
  },
  pricing: {
    introduction: "Three engagement options, scaled by scope and commitment.",
    options: [
      {
        name: "Option A: Full Execution",
        description:
          "MVRX Labs handles all initiatives end-to-end. Client provides engineering support and editorial sign-off.",
        components: [
          {
            component: "Technical SEO",
            detail: "Roadmap, specs, schema templates, ongoing audits",
            monthly: "\u00a31,500",
          },
          {
            component: "LinkedIn (founders + company)",
            detail: "8-10 posts/week total, ghostwriting",
            monthly: "\u00a32,500",
          },
          { component: "SEO blog content", detail: "2-4 articles/month (3,000+ words)", monthly: "\u00a32,000" },
          { component: "Link building", detail: "Stockist outreach, PR, expert content", monthly: "\u00a31,500" },
          {
            component: "Social SEO + Reddit",
            detail: "TikTok scripts, IG optimisation, Reddit",
            monthly: "\u00a31,000",
          },
          {
            component: "Reporting + AI visibility",
            detail: "Monthly reports, SoM tracking, benchmarks",
            monthly: "\u00a3500",
          },
        ],
        total: "\u00a39,000/month",
        note: "No minimum commitment. SEO takes 3+ months to show results; we recommend 6 months. 10% discount on 12-month agreements.",
      },
      {
        name: "Option B: Strategy + Content",
        description: "MVRX Labs handles content and strategic direction. Client executes technical SEO internally.",
        components: [
          {
            component: "LinkedIn (founders + company)",
            detail: "8-10 posts/week, ghostwriting",
            monthly: "\u00a32,500",
          },
          { component: "SEO blog content", detail: "2-4 articles/month", monthly: "\u00a32,000" },
          { component: "Social SEO + Reddit", detail: "TikTok scripts, IG, Reddit", monthly: "\u00a31,000" },
          { component: "Reporting + direction", detail: "Reports, tech SEO guidance", monthly: "\u00a3750" },
        ],
        total: "\u00a36,250/month",
        note: "No minimum commitment. We recommend at least 3 months for meaningful results.",
      },
      {
        name: "Option C: Advisory + Audit",
        description: "MVRX Labs provides strategic oversight and monthly audits. Client executes all workstreams.",
        components: [
          { component: "Monthly SEO audit", detail: "Automated crawl + analysis", monthly: "\u00a3750" },
          { component: "Monthly competitor benchmark", detail: "SimilarWeb + DR tracking", monthly: "\u00a3500" },
          { component: "Strategic advisory (4 hrs)", detail: "Bi-weekly calls, async support", monthly: "\u00a31,000" },
          { component: "Quarterly deep-dive", detail: "Full refresh of this report", monthly: "\u00a3750" },
        ],
        total: "\u00a33,000/month",
        note: "No minimum commitment. We recommend at least 3 months.",
      },
    ],
    exclusions: [
      "Engineering implementation: On-site code changes require client's engineering team.",
      "Paid advertising: Google Ads, Meta Ads, TikTok Ads are out of scope.",
      "Design/creative production: Video, graphics, photography. MVRX provides scripts and briefs.",
      "Google Search Console: Requires client to grant read-only access.",
    ],
  },
};
